@URL =  http://localhost:5167
@KEY = ...

GET {{URL}}/api/Users
X-API-KEY: {{KEY}}
Accept: application/json

###

GET {{URL}}/api/Users/6861971ca650203b7c881e90
X-API-KEY: {{KEY}}
Accept: application/json

###

POST {{URL}}/api/Users
X-API-KEY: {{KEY}}
Content-Type: application/json

{
    "name": "Adam",
    "password": "abc"
}

###

PUT {{URL}}/api/Users/686293714353758f4ae0a99a
X-API-KEY: {{KEY}}
Content-Type: application/json

{
  "name": "Krzychu",
  "password": "abc"
}

###

DELETE {{URL}}/api/Users/685fe3cfe3339fd5b405a83e
X-API-KEY: {{KEY}}