@URL =  http://localhost:5167

GET {{URL}}/api/Users
Accept: application/json

###

GET {{URL}}/api/Users/PUT_ID_HERE
Accept: application/json

###

POST {{URL}}/api/Users
Content-Type: application/json

{
  "user": {
    "name": "bot",
    "age": 69 
  }
}

###

PUT {{URL}}/api/Users/PUT_ID_HERE
Content-Type: application/json

{
  "id": "PUT_ID_HERE",
  "name": "sigmaBot",
  "age": 69
}

###

DELETE {{URL}}/api/Users/PUT_ID_HERE